<?php
/**
 * Created by PhpStorm.
 * User: khuen
 * Date: 11/18/2017
 * Time: 12:57 AM
 */

namespace Tests\Downloader;

use AppBundle\Entity\Link;
use Doctrine\DBAL\DBALException;
use Doctrine\ORM\EntityManager;
use DownloaderBundle\Downloader;
use GuzzleHttp\Client;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class DownloaderTest extends KernelTestCase
{
    /**
     * @var Downloader
     */
    protected $service;

    /**
     * @var EntityManager
     */
    private $em;

    /**
     * Set up the test
     */
    public function setUp()
    {
        self::bootKernel();
        $this->service = self::$kernel->getContainer()->get('downloader');
        $this->em = self::$kernel->getContainer()->get('doctrine.orm.entity_manager');
    }

    /**
     * Test download a web page
     */
    public function testDownload()
    {
//        try {
//            $this->service->download('https://www.pexels.com/photo/adult-beautiful-blue-bouquet-458627/');
//        } catch (\Exception $e) {
//            echo $e->getMessage() . "\n";
//        }

        $client = new Client([
            'timeout' => 10,
            'allow_redirects' => false,
            'verify' => false
        ]);

        $response = $client->get('https://geocode.xyz/', [
            'query' => [
                'scantext' => "Women's Black Zip Up Hooded Jacket pexels photo 54200",
                'json' => 1
            ]
        ]);

        $results = $response->getBody()->getContents();
        $resultObj = @json_decode($results);
    }

    /**
     * Tear down the test, reset test database
     */
    public function tearDown()
    {
        $query = "
            SET foreign_key_checks = 0;
            TRUNCATE Link;
            TRUNCATE Image;
            SET foreign_key_checks = 1;
        ";

        try {
            $this->em->getConnection()->query($query);
        } catch (DBALException $e) {
        }

        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}