<?php
/**
 * Created by PhpStorm.
 * User: khuen
 * Date: 11/18/2017
 * Time: 12:57 AM
 */

namespace Tests\Downloader;

use AppBundle\Entity\Link;
use Doctrine\DBAL\DBALException;
use Doctrine\ORM\EntityManager;
use DownloaderBundle\Downloader;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class DownloaderTest extends KernelTestCase
{
    /**
     * @var Downloader
     */
    protected $service;

    /**
     * @var EntityManager
     */
    private $em;

    /**
     * Set up the test
     */
    public function setUp()
    {
        self::bootKernel();
        $this->service = self::$kernel->getContainer()->get('downloader');
        $this->em = self::$kernel->getContainer()->get('doctrine.orm.entity_manager');
    }

    /**
     * Test download a web page
     */
    public function testDownload()
    {
        try {
            $this->service->download('https://www.locationscout.net/');
        } catch (\Exception $e) {
            echo $e->getMessage() . "\n";
        }
    }

    /**
     * Tear down the test, reset test database
     */
    public function tearDown()
    {
        $query = "
            SET foreign_key_checks = 0;
            TRUNCATE Link;
            TRUNCATE Image;
            SET foreign_key_checks = 1;
        ";

        try {
            $this->em->getConnection()->query($query);
        } catch (DBALException $e) {
        }

        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}