services:
    downloader:
        class: DownloaderBundle\Downloader
        arguments: ["@doctrine.orm.entity_manager", "@queue", "@helpers"]

    helpers:
        class: DownloaderBundle\Services\Helpers
        arguments: ["@helper.keyword", "@helper.url", '@helper.image']
    helper.keyword:
        class: DownloaderBundle\Services\Helpers\Keyword
        arguments: ["@doctrine.orm.entity_manager"]
    helper.url:
        class: DownloaderBundle\Services\Helpers\Url
    helper.image:
        class: DownloaderBundle\Services\Helpers\Image
        arguments: ['@kernel', '@doctrine.orm.entity_manager']
    helper.string:
        class: DownloaderBundle\Services\Helpers\String