services:
    downloader:
        class: DownloaderBundle\Downloader
        arguments: ["@doctrine.orm.entity_manager", "@queue", "@helpers", "@logger"]
        tags:
            - { name: monolog.logger, channel: crawler }

    helpers:
        class: DownloaderBundle\Services\Helpers
        arguments: ["@helper.keyword", "@helper.url", '@helper.image']
    helper.keyword:
        class: DownloaderBundle\Services\Helpers\Keyword
        arguments: ["@doctrine.orm.entity_manager"]
    helper.url:
        class: DownloaderBundle\Services\Helpers\Url
    helper.image:
        class: DownloaderBundle\Services\Helpers\Image
        arguments: ['@kernel', '@doctrine.orm.entity_manager', '@logger', '@helper.keyword']
        tags:
            - { name: monolog.logger, channel: crawler }
    helper.string:
        class: DownloaderBundle\Services\Helpers\String