<?php

namespace AppBundle\Repository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * GeoNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeonameRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Check if a word contains in a city name
     *
     * @param $word
     * @return bool
     */
    public function isCityName($word)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('count(c.id)');
        $qb->where('c.name = :word')
            ->orWhere('c.asciiName = :word')
            ->orWhere('c.alternateNames LIKE :wildword');
        $qb->andWhere('c.featureClass = :featureclass');
        $qb->setParameter('word', "{$word}");
        $qb->setParameter('wildword', "[,]{$word}_");
        $qb->setParameter('featureclass', "P");

        try {
            $count = $qb->getQuery()->getSingleScalarResult();

            return $count > 0;
        } catch (NoResultException $e) {
            return false;
        } catch (NonUniqueResultException $e) {

        }

        return false;
    }
}
