<?php

namespace AppBundle\Repository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * GeoNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoNameRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Check if a word contains in a city name
     *
     * @param $word
     * @return bool
     */
    public function isInCityName($word)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('count(c.id)');
        $qb->where('c.name LIKE :word')
            ->orWhere('c.asciiName LIKE :word')
            ->orWhere('c.alternateNames LIKE :word');
        $qb->setParameter('word', "%{$word}%");

        try {
            $count = $qb->getQuery()->getSingleScalarResult();

            return $count > 0;
        } catch (NoResultException $e) {
            return false;
        } catch (NonUniqueResultException $e) {

        }

        return false;
    }
}
