<?php

namespace AppBundle\Repository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMostRelevantLink()
    {
        $qb = $this->createQueryBuilder('l');
        $qb->select('l, MAX(l.relevance) as HIDDEN max_relevance')
            ->setMaxResults(1)
            ->orderBy('max_relevance', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
