<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Link;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the most relevant yet unvisited link
     *
     * @return Link|bool
     */
    public function getLastUnvisitedLink()
    {
        $qb = $this->createQueryBuilder('l')
            ->where('l.visited = :unvisited')
            ->setParameter('unvisited', false)
            ->orderBy('l.relevance', 'DESC')
            ->setMaxResults(1)
            ->getQuery();

        try {
            return $qb->getSingleResult();
        } catch (\Exception $e) {
            return false;
        }
    }

    /**
     * Get number of links
     *
     * @return mixed|null
     */
    public function getNumberOfLinks()
    {
        $query = $this->createQueryBuilder('l')
            ->select('COUNT(l.id)')
            ->getQuery();

        try {
            return $query->getSingleScalarResult();
        } catch (\Exception $e) {
            return null;
        }
    }

    /**
     * Get number of visited links
     *
     * @return mixed|null
     */
    public function getNumberOfVisitedLinks()
    {
        $query = $this->createQueryBuilder('l')
            ->select('COUNT(l.id)')
            ->where('l.visited = true')
            ->getQuery();

        try {
            return $query->getSingleScalarResult();
        } catch (\Exception $e) {
            return null;
        }
    }
}
