<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Link;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the most relevant yet unvisited link
     *
     * @return Link|bool
     */
    public function getSeedLink()
    {
        $qb = $this->createQueryBuilder('l')
            ->where('l.visited = :unvisited')
            ->setParameter('unvisited', false)
            ->orderBy('l.relevance', 'DESC')
            ->setMaxResults(1)
            ->getQuery();

        try {
            return $qb->getSingleResult();
        } catch (\Exception $e) {
            return false;
        }
    }
}
