<?php

namespace AppBundle\Repository;

/**
 * SeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeedRepository extends \Doctrine\ORM\EntityRepository
{
}
