<?php

namespace AppBundle\Repository;

/**
 * StopwordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StopwordRepository extends \Doctrine\ORM\EntityRepository
{
}
