<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UrlQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlQueueRepository extends EntityRepository
{
    /**
     * Check whether the queue is empty
     *
     * @return bool
     */
    public function isEmpty()
    {
        $qb = $this->createQueryBuilder('q');
        $result = $qb->select($qb->expr()->count('q.id'))
            ->getQuery()->getSingleScalarResult();

        return ($result == 0);
    }

    public function addLink($link)
    {

    }

    public function addLinks($links)
    {

    }
}
