downloader:
    resource: "@DownloaderBundle/Resources/config/routing.yml"
    prefix:   /

queue:
    resource: "@QueueBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
