fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

gui:
    resource: "@GuiBundle/Resources/config/routing.yml"
    prefix:   /
