# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    # Services

    # Helpers
    hlp.string:
        class: AppBundle\Services\Helpers\String

    hlp.url:
        class: AppBundle\Services\Helpers\Url

    # Components
    cpn.queue:
        class: AppBundle\Components\Queue
        arguments: []

    cpn.crawler:
        class: AppBundle\Components\Crawler
        arguments: ['@doctrine.orm.entity_manager', '@cpn.queue']

    cpn.downloader:
        class: AppBundle\Components\Downloader
        arguments: ['@logger','@doctrine.orm.entity_manager', '@hlp.string', '@hlp.url']
        tags:
            - { name: monolog.logger, channel: imc }