<?php

namespace QueueBundle\Repository;
use Symfony\Component\Security\Acl\Exception\Exception;

/**
 * QueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find the most relevance link
     *
     * @return bool|mixed
     */
    public function findMostRelevanceLink()
    {
        $qb = $this->createQueryBuilder('l')
            ->select('MAX(l.relevance)')
            ->from('QueryBundle:Link', 'l')
            ->orderBy('l.relevance', 'DESC')
            ->setMaxResults(1)
            ->getQuery();

        try {
            return $qb->getSingleResult();
        } catch (Exception $e) {
            return false;
        }
    }
}
