list_images:
    path: /
    defaults: { _controller: AppBundle:Api\Image:list, _format: json }
    methods: GET
read_image:
    path: /{id}
    defaults: { _controller: AppBundle:Api\Image:read, _format: json }
    methods: GET
update_image:
    path: /{id}
    defaults: { _controller: AppBundle:Api\Image:update, _format: json }
    methods: PUT
delete_image:
    path: /{id}
    defaults: { _controller: AppBundle:Api\Image:delete, _format: json }
    methods: DELETE