gallery_index:
    path:     /
    defaults: { _controller: "GuiBundle:Gallery:index" }
    methods:  GET
    options:
        expose: true

gallery_view:
    path:     /{id}/view
    defaults: { _controller: "GuiBundle:Gallery:view" }
    methods:  GET
    options:
        expose: true

gallery_edit:
    path:     /{id}/edit
    defaults: { _controller: "GuiBundle:Gallery:edit" }
    methods:  [GET, POST]
    options:
        expose: true

gallery_delete:
    path:     /{id}/delete
    defaults: { _controller: "GuiBundle:Gallery:delete" }
    options:
        expose: true