services:
    image_manager:
        class: AppBundle\Services\ImageManager
        arguments: ["@doctrine.orm.entity_manager","@kernel", "@logger", "@knp_paginator", '@session']
        tags:
            - { name: monolog.logger, channel: managers }