services:
    image_manager:
        class: AppBundle\Services\ImageManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@kernel"
            - "@logger"
            - "@knp_paginator"
            - '@session'
            - '@request_stack'
        tags:
            - { name: monolog.logger, channel: managers }

    task_manager:
        class: AppBundle\Services\TaskManager
        arguments:
            - "@doctrine.orm.entity_manager"

    image_serialization_subscriber:
        class: AppBundle\EventSubscribers\ImageSerializationSubscriber
        arguments: ['@request_stack']
        tags:
            - { name: jms_serializer.event_subscriber }

    flickr:
        class: AppBundle\Services\Flickr
        arguments: ['@service_container']