AppBundle\Entity\Country:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CountryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        iso:
            type: string
            length: '2'
        iso3:
            type: string
            length: '3'
        isoNumeric:
            type: string
            length: '3'
            column: iso_numeric
        fips:
            type: string
            length: '2'
            nullable: true
        country:
            type: string
            length: 255
        capital:
            type: string
            length: 255
            nullable: true
        area:
            type: bigint
        population:
            type: string
            length: 255
        continent:
            type: string
            length: '2'
        tld:
            type: string
            length: 255
        currencyCode:
            type: string
            length: '3'
            column: currency_code
        currencyName:
            type: string
            length: 255
            column: currency_name
        phone:
            type: string
            length: 255
        postalCodeFormat:
            type: string
            length: 255
            column: postal_code_format
        postalCodeRegex:
            type: string
            length: 255
            column: postal_code_regex
        languages:
            type: string
            length: 255
        geonameid:
            type: integer
        neighbours:
            type: string
            length: 255
        equivalentFipsCode:
            type: string
            length: 255
            column: equivalent_fips_code
    lifecycleCallbacks: {  }
