AppBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        src:
            type: string
            length: '512'
            unique: true
        alt:
            type: string
            length: '512'
            nullable: true
        filename:
            type: string
            length: 255
        path:
            type: string
            length: '512'
            nullable: true
        width:
            type: integer
        height:
            type: integer
        type:
            type: string
            length: '5'
        isExifLocation:
            type: boolean
            nullable: true
            column: is_exif_location
        latitude:
            type: decimal
            precision: 10
            scale: '6'
            nullable: true
        longitude:
            type: decimal
            precision: 10
            scale: '6'
            nullable: true
        address:
            type: string
            length: '512'
            nullable: true
        description:
            type: string
            length: '512'
            nullable: true
        metadata:
            type: text
        geoparsed:
            type: boolean
    lifecycleCallbacks: {  }
