AppBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        page:
            targetEntity: AppBundle\Entity\Page
            inversedBy: images
            joinColumn:
                name: page_id
                referenceColumnName: id
        location:
            targetEntity: AppBundle\Entity\Location
            inversedBy: images
            joinColumn:
                name: location_id
                referenceColumnName: id
    fields:
        hash:
            type: string
            length: 255
        src:
            type: string
            length: '1024'
        alt:
            type: string
            length: '512'
            nullable: true
        filename:
            type: string
            length: 255
        path:
            type: string
            length: '512'
        width:
            type: integer
        height:
            type: integer
        type:
            type: string
            length: '5'
        author:
            type: string
            length: '128'
            nullable: true
        copyright:
            type: string
            length: 512
            nullable: true
        isExifLocation:
            type: boolean
            nullable: true
            column: is_exif_location
        dateTaken:
            type: datetime
            nullable: true
            column: date_taken
        dateAcquired:
            type: datetime
            nullable: true
            column: date_acquired
    lifecycleCallbacks: {  }
