AppBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        source:
            targetEntity: AppBundle\Entity\Link
            joinColumn:
                name: source
                referenceColumnName: url
    fields:
        src:
            type: string
            length: '512'
            unique: true
        alt:
            type: string
            length: '512'
            nullable: true
        filename:
            type: string
            length: 255
        path:
            type: string
            length: '512'
            nullable: true
        width:
            type: integer
        height:
            type: integer
        type:
            type: string
            length: '5'
        author:
            type: string
            length: '128'
            nullable: true
        copyright:
            type: string
            length: 512
            nullable: true
        isExifLocation:
            type: boolean
            nullable: true
            column: is_exif_location
        dateTaken:
            type: datetime
            nullable: true
            column: date_taken
        dateAcquired:
            type: datetime
            nullable: true
            column: date_acquired
        latitude:
            type: decimal
            precision: 10
            scale: '6'
            nullable: true
        longitude:
            type: decimal
            precision: 10
            scale: '6'
            nullable: true
        altitude:
            type: decimal
            precision: 10
            scale: '6'
            nullable: true
        address:
            type: string
            length: '512'
            nullable: true
        zipcode:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 255
            nullable: true
        metadata:
            type: text
    lifecycleCallbacks: {  }
