AppBundle\Entity\Link:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LinkRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: text
        title:
            type: string
            length: 255
        visited:
            type: boolean
            default: false
        relevance:
            type: float
    lifecycleCallbacks: {  }
