AppBundle\Entity\Link:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LinkRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            length: '512'
            unique: true
        title:
            type: string
            length: 255
        relevance:
            type: float
    lifecycleCallbacks: {  }
