AppBundle\Entity\Link:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LinkRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        page:
            targetEntity: AppBundle\Entity\Page
            joinColumn:
                name: page_id
                referenceColumnName: id
    fields:
        url:
            type: string
            length: '512'
            unique: false
        title:
            type: string
            length: 255
        visited:
            type: boolean
        relevance:
            type: float
    lifecycleCallbacks: {  }
