AppBundle\Entity\Page:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        links:
            targetEntity: AppBundle\Entity\Link
            mappedBy: AppBundle\Entity\Page
        images:
            targetEntity: AppBundle\Entity\Image
            mappedBy: AppBundle\Entity\Page
        keywords:
            targetEntity: AppBundle\Entity\Keyword
            mappedBy: AppBundle\Entity\Page
    oneToOne:
        text:
            targetEntity: AppBundle\Entity\Text
            joinColumn:
                name: text_id
                referencedColumnName: id
    manyToOne:
        parent:
            targetEntity: AppBundle\Entity\Page
            joinColumn:
                name: parent_id
                referenceColumnName: id
    fields:
        url:
            type: string
            length: '512'
        host:
            type: string
            length: 255
        title:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
