AppBundle\Entity\Page:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        links:
            targetEntity: AppBundle\Entity\Link
            mappedBy: page
        images:
            targetEntity: AppBundle\Entity\Image
            mappedBy: page
        keywords:
            targetEntity: AppBundle\Entity\Keyword
            mappedBy: page
    oneToOne:
        text:
            targetEntity: AppBundle\Entity\Text
            joinColumn:
                name: text_id
                referencedColumnName: id
    manyToOne:
        parent:
            targetEntity: AppBundle\Entity\Page
            joinColumn:
                name: parent_id
                referenceColumnName: id
    fields:
        url:
            type: string
            length: '512'
            unique: true
        host:
            type: string
            length: 512
        title:
            type: string
            length: 512
            nullable: true
    lifecycleCallbacks: {  }
