AppBundle\Entity\Stopword:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\StopwordRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        hash:
            type: string
            length: 255
        word:
            type: string
            length: 255
    lifecycleCallbacks: {  }
