AppBundle\Entity\Text:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TextRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        page:
            targetEntity: AppBundle\Entity\Page
            joinColumn:
                name: page_id
                referencedColumnName: id
    fields:
        content:
            type: text
    lifecycleCallbacks: {  }
