AppBundle\Entity\UrlQueue:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UrlQueueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        parentId:
            type: integer
            column: parent_id
        seedId:
            type: integer
            column: seed_id
        url:
            type: string
            length: '512'
        urlTitle:
            type: string
            length: '512'
            column: url_title
        host:
            type: string
            length: 255
        relevance:
            type: float
    lifecycleCallbacks: {  }
