gui_homepage:
    path: /
    defaults: { _controller: GuiBundle:Default:index }
    options:
        expose: true

gui_task:
    prefix: /tasks
    resource: "@GuiBundle/Resources/config/routing/task.yml"

gui_gallery:
    prefix: /gallery
    resource: "@GuiBundle/Resources/config/routing/gallery.yml"

gui_statistics:
    resource: "@GuiBundle/Resources/config/routing/statistics.yml"

gui_verification:
    prefix: /verification
    resource: "@GuiBundle/Resources/config/routing/verification.yml"

gui_test:
    path: /test
    defaults: { _controller: GuiBundle:Default:test }
    options:
        expose: true

gui_clear_cache:
    path: /clear_cache
    defaults: { _controller: GuiBundle:Default:clearCache }
    options:
        expose: true
