gui_homepage:
    path: /
    defaults: { _controller: GuiBundle:Default:index }
    options:
        expose: true

gui_statistics:
    path: /statistics
    defaults: { _controller: GuiBundle:Default:stats }
    options:
        expose: true

gui_gallery:
    prefix: /gallery
    resource: "@GuiBundle/Resources/config/routing/gallery.yml"

gui_verification:
    prefix: /verification
    resource: "@GuiBundle/Resources/config/routing/verification.yml"

gui_clear_cache:
    path: /clear_cache
    defaults: { _controller: GuiBundle:Default:clearCache }
    options:
        expose: true