gui_homepage:
    path:     /
    defaults: { _controller: GuiBundle:Default:index }

gui_verification:
    resource: "@GuiBundle/Resources/config/routing/verification.yml"
    prefix:   /verification

gui_clear_cache:
    path:   /
    defaults: { _controller: GuiBundlerCache }